
/**************************************************************
 *	
 *	ghostHouse, 8 bit, 11025Hz,
 *	1 channel, 1311552 bytes/channel
 *	Total Size: 1 * 1311552 + 4 (header) = 1311596 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/davidhan/Documents/cs2261/_Final Project/FINAL/ghostHouse.wav
 *	Time-stamp: Fri Apr 28 23:50:08 2017
 *	
 **************************************************************/

#ifndef __GHOSTHOUSEH__
#define __GHOSTHOUSEH__

#define GHOSTHOUSEFREQ 11025
#define GHOSTHOUSELEN 1311552

extern const unsigned char ghostHouse[1311552];

#endif /* __GHOSTHOUSEH__ */
