
/**************************************************************
 *	
 *	jump, 8 bit, 11025Hz,
 *	1 channel, 6506 bytes/channel
 *	Total Size: 1 * 6506 + 4 (header) = 6550 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/davidhan/Documents/cs2261/_Final Project/M03/jump.wav
 *	Time-stamp: Tue Apr 04 22:00:54 2017
 *	
 **************************************************************/

#ifndef __JUMPH__
#define __JUMPH__

#define JUMPFREQ 11025
#define JUMPLEN 6506

extern const unsigned char jump[6506];

#endif /* __JUMPH__ */
