
/**************************************************************
 *	
 *	opening, 8 bit, 11025Hz,
 *	1 channel, 970105 bytes/channel
 *	Total Size: 1 * 970105 + 4 (header) = 970149 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/davidhan/Documents/cs2261/_Final Project/M03/opening.wav
 *	Time-stamp: Tue Apr 04 21:47:10 2017
 *	
 **************************************************************/

#ifndef __OPENINGH__
#define __OPENINGH__

#define OPENINGFREQ 11025
#define OPENINGLEN 970105

extern const unsigned char opening[970105];

#endif /* __OPENINGH__ */
